version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/PycharmProjects
    steps:
      - checkout:
          path: ~/PycharmProjects/bqueryd
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check docker-compose version
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Start Services
          working_directory: bqueryd
          command: |
            docker-compose -f docker-compose.yml up --build -d
      - run:
          name: Sleep 30 seconds waiting for localstack service building
          command: sleep 30
      - run:
          name: Run Tests
          working_directory: bqueryd
          command: docker-compose -f docker-compose.yml run bqueryd pytest -vs tests --junitxml=test-results/pytest/pytest-report.xml --cov-report xml:test-results/pytest-cov/coverage.xml --cov=bqueryd
      - run:
          name: Stop Services
          command: docker-compose down
          working_directory: bqueryd
#     - name: Upload Coverage
#         command: python-codacy-coverage -r test-results/pytest-cov/coverage.xml
#         working_directory: bqueryd
      - store_test_results:
          path: bqueryd/test-results
      - store_artifacts:
          path: bqueryd/test-results
          destination: tr1
  
  pypi_release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Twine
          command: sudo pip install twine
      - run:
          name: Package Project
          command: sudo python setup.py sdist bdist_wheel
      - run:
          name: Upload to Pypi
          command: sudo twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*  

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - pypi_release:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/